<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="MAIN" Id="{d70c0d43-1e12-4f89-90c8-3d2f54cc3033}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	// develop branch
	fbReadFile			:FB_ReadFile;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbReadFile();]]></ST>
    </Implementation>
    <Method Name="INIT" Id="{5a5b2406-f2b5-458a-82e4-eedff343e569}">
      <Declaration><![CDATA[METHOD INIT
VAR
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="MAIN">
      <LineId Id="1049" Count="0" />
    </LineIds>
    <LineIds Name="MAIN.INIT">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>