name: Overwrite some file

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Set CURRENT_BRANCH
        run: |
          
          
          echo "COMMIT: " git describe --tags `git rev-list --tags --max-count=1`
          echo "TAG: " git describe --tags 3c3311f
          
