name: "CI"
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  image-analysis:
    name: Analyze image
    runs-on: ubuntu-18.04
    permissions:
      security-events: write
    steps:
      - name: Get Release Info
        uses: octokit/request-action@v2.x
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: GET /repos/{org_repo}/releases/tags/{tag}

      - name: Get Information from Release
        run: |
          echo '${{ steps.release.outputs.data }}' > release.json
          jq -r '.assets[].browser_download_url' release.json > assets.txt
          jq -r '.body' release.json > changelog.txt
