name: "CI"
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  image-analysis:
    name: Analyze image
    runs-on: ubuntu-18.04
    permissions:
      security-events: write
    steps:
      - name: Create grype configuration
        run: |
          cat <<EOF > $HOME/.grype.yaml
          ignore:
            # False positive, see https://github.com/anchore/grype/issues/558
            - vulnerability: CVE-2015-5237
              fix-state: unknown
              package:
                name: google.golang.org/protobuf
                version: v1.26.0
                type: go-module
                location: "/manager"
          EOF
      - name: Scan operator image
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: "qserv/qserv-operator:2022.1.1-rc1"
          acs-report-enable: true
          fail-build: false
