name: Overwrite some file

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Get TAG
        env:
          TAG: ""
        run: git tag --list | sort -V | tail -n1
      
      - name: Set the value
        id: step_one
        run: |
            echo "FOO=$(git status)" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
            echo "${{ env.FOO }}"
        
      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"            
        with:
          path: file.txt
          write-mode: overwrite
          
          # name of the variable
          contents: |
            $TAG
            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          message: 'Overwritten by Github Actions - ${date}'
