name: "CI"
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  image-analysis:
    name: Analyze image
    runs-on: ubuntu-18.04
    permissions:
      security-events: write
    steps:
      - name: get tag
        run: |
          # GitHub CLI api
          # https://cli.github.com/manual/gh_api

          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/OWNER/REPO/tags/protection
            
      - name: Get Release Info
        uses: octokit/request-action@v2.x
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: GET /repos/ECCO-RUO/test-branches-config-file/tags/{tag}

      - name: Get Information from Release
        env:
          DATA: ${{ steps.release.outputs.data }}
        run: |
          jq -r '.assets[].browser_download_url' <<<"$DATA" > assets.txt
          jq -r '.body' <<<"$DATA" > changelog.txt
