name: Overwrite some file

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # creates JSON file job
      - name: Create JSON file job
        uses: schdck/create-env-json@v1
        with:
          file-name: 'testFile.txt'

          # fill JSON with workflow data
          Repository: ${{ github.event.repository.name }}
          Branch: ${{ GITHUB.REF }}
          DATE: "${{ STEPS.CURRENT-TIME.OUTPUTS.READABLETIME }}"
          Project: ${{ GITHUB.REPOSITORY }}
          Engineer: ${{ GITHUB.ACTOR }}
          Server: ${{ RUNNER.OS }}
    # GIT commands
      - run: |
          git config user.email "ruo@ecco.com";
          git config user.name "ECCO-RUO"; 
          git add .;
          git commit -a -m "TXT created!";
          git push -u origin master;
