name: "CI"
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  image-analysis:
    name: Analyze image
    runs-on: ubuntu-18.04
    permissions:
      security-events: write
    steps:            
      - name: Get Release Info
        uses: "finnp/create-file-action@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_NAME: "dir/fileName.txt"
          FILE_DATA: "file content"
