name: Overwrite some file

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Get tag
        run: |
          echo '::step-output name=CURRENT_TAG::(git ls-remote --tags --sort=committerdate | grep -o 'v.*' | sort -r | head -1)'
          
      - name: Use tag
        run: echo ${{env.CURRENT_TAG}}
        
      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"            
        with:
          path: file.txt
          write-mode: overwrite
          
          # name of the variable
          contents: |
            ${{env.CURRENT_TAG}}
            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          message: 'Overwritten by Github Actions - ${date}'
