name: REPO DATA

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
        
      - name: Set VARS
        run: |
          echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "CURRENT_TAGGED_COMMIT=$(git rev-list --tags --max-count=1)" >> $GITHUB_ENV          
          echo "CURRENT_TAG=$(git describe --tags ${{ENV.CURRENT_TAGGED_COMMIT}})" >> $GITHUB_ENV
          
      - name: setvar
        id: v
        run: |
          echo "::set-output name=newTAG::$(git describe --tags ${{ENV.CURRENT_TAGGED_COMMIT}})" >> $GITHUB_OUTPUT
          
      - name: Write TXT file
        uses: "DamianReeves/write-file-action@master"            
        with:
          path: repo_data.txt
          write-mode: overwrite
          contents: |
            - - - # # #  REPO DATA # # # - - -
            * BRANCH: ${{ENV.CURRENT_BRANCH}}
            * COMMIT: ${{ENV.CURRENT_TAGGED_COMMIT}}
            * TAG: ${{ENV.CURRENT_TAG}}
            
            newTAG: ${{STEPS.V.OUTPUTS.newTAG}}
            
            
