name: REPO DATA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
        
      - name: Set CURRENT_BRANCH
        id: vars
        run: |
          echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
          echo "CURRENT_TAGGED_COMMIT=$(git rev-list --tags --max-count=1)" >> $GITHUB_OUTPUT
          echo "::set-output name=CURRENT_TAG::$(git describe --tags ${{ENV.CURRENT_TAGGED_COMMIT}})"
          
          echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
          echo "ENV_TAGGED_COMMIT=$(git describe --tags ${{ENV.CURRENT_TAGGED_COMMIT}})" >> $GITHUB_OUTPUT
          echo "ENV_VAR=GITHUB_OUTPUT" >> $GITHUB_OUTPUT
                              
      - name: Write TXT file
        uses: "DamianReeves/write-file-action@master"            
        with:
          path: repo_data.txt
          write-mode: overwrite
          contents: |
            - - - # # #  REPO DATA # # # - - -
            * BRANCH: ${{STEPS.VARS.OUTPUTSCURRENT_BRANCH}}
            * COMMIT: ${{STEPS.VARS.OUTPUTS.CURRENT_TAGGED_COMMIT}}
            * TAG: ${{STEPS.VARS.OUTPUTS.CURRENT_TAG}}
           
            * ENV_TAGGED_COMMIT: ${{STEPS.VARS.OUTPUTS.GITHUB_ENV_TAGGED_COMMIT}}
            * ENV_VAR: ${{STEPS.VARS.OUTPUTS.GITHUB_ENV_VAR}}
            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          message: 'Overwritten by Github Actions'
